# Generated by Django 3.2.25 on 2024-07-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoomdata',
            old_name='zoom_x',
            new_name='zoom_position_x',
        ),
        migrations.RenameField(
            model_name='zoomdata',
            old_name='zoom_y',
            new_name='zoom_position_y',
        ),
        migrations.RemoveField(
            model_name='zoomdata',
            name='created_at',
        ),
    ]
